# Generated by Django 5.1.4 on 2024-12-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0003_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
